### PR TITLE
Use GetEntInfo everywhere possible

### PR DESCRIPTION
**Pull request by DizzyEggg**
Follow-up to #245

All places now use `GetEntInfo`

### CODE REVIEW

**Comment by Kermalis** [comment]
This isn't related to your work, but to Mateon's:
I have a pet-peeve of multiple GetEntInfo calls like this:
```c
if (GetEntInfo(pokemon)->sleep.sleep != STATUS_SLEEP &&
        GetEntInfo(pokemon)->sleep.sleep != STATUS_NAPPING &&
        GetEntInfo(pokemon)->sleep.sleep != STATUS_NIGHTMARE)
    {
        return FALSE;
    }
```

Can you attempt to make locals out of these repeated ones?
```c
EntityInfo *inf = GetEntInfo(pokemon);
if (inf->sleep.sleep != STATUS_SLEEP &&
        inf->sleep.sleep != STATUS_NAPPING &&
        inf->sleep.sleep != STATUS_NIGHTMARE)
    {
        return FALSE;
    }
```
There are also some in new scopes (after EntityExists calls) that are also repeated like this.
```c
if (EntityExists(target)) {
    if (GetEntInfo(target)->powerEars != 0) {
        ...
    }
    else {
        GetEntInfo(target)->powerEars = 1;
        ...
    }
}
```

It'd just look cleaner and it might actually matter for matching in at least 1 instance

**Comment by DizzyEggg** [comment]
> This isn't related to your work, but to Mateon's: I have a pet-peeve of multiple GetEntInfo calls like this:
> It'd just look cleaner and it might actually matter for matching in at least 1 instance (eventually)

It depends on the function, I know in some cases it won't match if it's done like you say, but in others it probably doesn't matter. Do you have function names which do that?

**Comment by Kermalis** [comment]
I don't have a list. I was just looking through the changes in the last PR and found the uses that way. If I was at home I'd just do a search in all .c files for GetEntInfo and scroll through

**Comment by AnonymousRandomPerson** [comment]
Merge conflicts with the string format PR.

**Comment by DizzyEggg** [comment]
> Merge conflicts with the string format PR.

Conflicts solved

**Review by SethBarberee — APPROVED** [review]

**Pull request merged**
